// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.30.0

package database

import (
	"time"

	"github.com/google/uuid"
)

type Portfolio struct {
	ID            uuid.UUID
	UserID        uuid.UUID
	StockID       uuid.UUID
	TotalQuantity string
	CreatedAt     time.Time
	UpdatedAt     time.Time
}

type Stock struct {
	ID          uuid.UUID
	StockSymbol string
	Valuation   string
}

type StockTransaction struct {
	ID              uuid.UUID
	UserID          uuid.UUID
	StockID         uuid.UUID
	Type            string
	Quantity        string
	Price           string
	TransactionType string
	CreatedAt       time.Time
}

type User struct {
	ID        uuid.UUID
	Name      string
	Email     string
	Password  string
	CreatedAt time.Time
	UpdatedAt time.Time
}
