// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.30.0

package database

import (
	"database/sql"

	"github.com/google/uuid"
)

type Stock struct {
	ID          uuid.UUID
	StockSymbol string
	Valuation   sql.NullString
}

type User struct {
	ID             uuid.UUID
	Name           string
	Email          string
	Isreferral     sql.NullBool
	Referraluserid uuid.NullUUID
}
